# Polynomial Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data_E_Peak.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Polynomial Regression model on the Training set

In [4]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [5]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((X_test,y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 6.5  27.93 28.3 ]
 [13.5  35.   34.65]
 [36.   43.42 43.17]
 [18.6  37.43 37.43]
 [29.5  41.4  41.44]
 [22.4  38.8  39.05]
 [31.6  42.16 42.03]
 [29.4  41.36 41.41]
 [11.1  33.27 32.95]
 [20.7  38.2  38.36]
 [15.3  36.   35.74]
 [ 4.8  24.99 25.67]
 [13.3  34.88 34.52]
 [31.8  42.23 42.09]
 [25.8  40.02 40.27]
 [ 7.   28.68 28.94]
 [ 7.9  29.91 29.99]
 [17.9  37.16 37.1 ]
 [26.6  40.31 40.54]
 [ 6.3  27.62 28.03]
 [33.7  42.85 42.59]
 [25.6  39.95 40.21]
 [38.4  43.67 43.73]
 [ 8.7  30.89 30.83]
 [36.5  43.51 43.29]
 [17.   36.79 36.65]
 [30.9  41.91 41.84]
 [17.3  36.91 36.8 ]
 [22.5  38.84 39.08]
 [22.7  38.91 39.16]
 [29.8  41.51 41.53]
 [33.5  42.79 42.54]
 [35.1  43.23 42.95]
 [34.5  43.08 42.8 ]
 [ 1.7  17.75 16.65]
 [ 1.2  16.32 13.62]
 [36.8  43.55 43.36]
 [32.7  42.54 42.33]
 [24.3  39.48 39.75]
 [15.7  36.2  35.96]
 [11.3  33.44 33.1 ]
 [ 7.1  28.83 29.07]
 [29.3  41.32 41.38]
 [ 2.1  18.84 18.49]
 [ 3.7  22.72 23.41]
 [ 5.6  26.45 27.  ]
 [ 7.6  29.52 29.66]
 [15.2  35.95

## Evaluating the Model Performance

In [6]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9962608351967658